In [ ]:
import numpy as np

In [ ]:
#1D np array
a = np.array([1,2,3,4])
print(a)

In [ ]:
#2d np array
b = np.array([[1,2,3,4],
              [2,3,4,5],
              [3,4,5,6]], dtype = 'int32')
print(b)

In [ ]:
#get dimension and shapes
a.ndim
b.ndim
a.shape
b.shape

In [ ]:
#get type
a.dtype

In [ ]:
#get size
b.itemsize

In [ ]:
c = np.array([[1,2,3,4,8,5,6],
              [2,3,4,5,4,5,6,],
              [3,4,5,6,2,5,6]], dtype='int32')
print(c)
c.shape

In [ ]:
#get a specifiq element [r,c]
c[0,3]
c[0,-4]

In [ ]:
#get a specifiq row
c[0, :]

In [ ]:
#get a specifiq column
c[:, 0]

In [ ]:
#startindex:endingintex:stepsize
c[0, 1:6:2]

In [ ]:
#change an element
c[1,4] = 69
print(c)

In [ ]:
#3d array
d = np.array([[[1,2,3,4,8,5,6],
               [2,3,4,5,4,5,6,]],

              [[3,4,5,6,2,5,6],
               [6,5,2,3,6,7,4]]], dtype='int32')
print(d)

In [ ]:
#get element from 3d array (get the dimensions)
d[0,1,:]

In [ ]:
#replace


In [ ]:
#different type of presentations with numpy
#All 0s Matrix
np.zeros((2,5,4), dtype = 'int32')

In [ ]:
#any other number
np.full(a.shape, 4)

In [ ]:
#Random number
#np.random.rand(3,2,1)
np.random.randint(7, size = (4,4))

In [ ]:
#Identity Matrix
np.identity(3)

In [ ]:
arr = np.array([1,2,3])
r = np.repeat(arr, 3 , axis = 0)
print(r)

In [77]:
#Initializing a Matrix
a1 = np.ones((5,5))
print(a1)

a2 = np.zeros((3,3))
a2[1,1] = 9
print(a2)

a1[1:-1, 1:-1] = a2
print(a1)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
